# ======================================================================
# usage for interactive sessions: 
# $ docker-compose run --service-ports devenv bash
# ======================================================================
version: "3"
services: 
  devenv: 
    image: karenyng/miniconda3_devenv:latest
    volumes:
      - ~/Documents/Projects/:/root/Software/Projects
    ports:
      - "42424-42434"
